import HomePage from '@/components/home/Home';
import Pathfinding from '@/components/pathfinding/Pathfinding';
import Sort from '@/components/sort/Sort';
import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
  const [visualizeAlgo, setVisualizeAlgo] = useState(0);

  return (
    <>
      <Head>
        <title>Visualize Algorithms</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header className="flex justify-center gap-6">
        <button onClick={() => setVisualizeAlgo(1)}>
          Visualize Sorting Algorithms
        </button>
        <button onClick={() => setVisualizeAlgo(2)}>
          Visualize Pathfinding Algorithms
        </button>
      </header>
      <main className="mt-6 flex justify-center">
        {visualizeAlgo === 1 ? (
          <Sort />
        ) : visualizeAlgo === 2 ? (
          <Pathfinding />
        ) : (
          <HomePage />
        )}
      </main>
    </>
  );
}
